### ISSUE TITLE
class com.bumptech.glide.load.engine.GlideException: Failed to load resource

### ISSUE THREAD

**Issue by tudosxxx** [bhagyashreekhatri/flutter_social_content_share#29]
W/Glide   (22056): Load failed for https://post.healthline.com/wp-content/uploads/2020/09/healthy-eating-ingredients-732x549-thumbnail-732x549.jpg with size [-2147483648x-2147483648]
W/Glide   (22056): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
W/Glide   (22056): There was 1 cause:
W/Glide   (22056): javax.net.ssl.SSLHandshakeException(Chain validation failed)
W/Glide   (22056):  call GlideException#logRootCauses(String) for more detail
W/Glide   (22056):   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
W/Glide   (22056): There was 1 cause:
W/Glide   (22056): javax.net.ssl.SSLHandshakeException(Chain validation failed)
W/Glide   (22056):  call GlideException#logRootCauses(String) for more detail
W/Glide   (22056):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
W/Glide   (22056): There was 1 cause:
W/Glide   (22056): javax.net.ssl.SSLHandshakeException(Chain validation failed)
W/Glide   (22056):  call GlideException#logRootCauses(String) for more detail
W/Glide   (22056):       Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: Chain validation failed
I/Glide   (22056): Root cause (1 of 1)
I/Glide   (22056): javax.net.ssl.SSLHandshakeException: Chain validation failed
I/Glide   (22056): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:236)
I/Glide   (22056): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1480)
I/Glide   (22056): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1424)
I/Glide   (22056): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1368)
I/Glide   (22056): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
I/Glide   (22056): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
I/Glide   (22056): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
I/Glide   (22056): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
I/Glide   (22056): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
I/Glide   (22056): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:470)
I/Glide   (22056): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
I/Glide   (22056): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
I/Glide   (22056): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
I/Glide   (22056): 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:100)
I/Glide   (22056): 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:56)
I/Glide   (22056): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (22056): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:164)
I/Glide   (22056): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:154)
I/Glide   (22056): 	at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:62)
I/Glide   (22056): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   (22056): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
I/Glide   (22056): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
I/Glide   (22056): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
I/Glide   (22056): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:276)
I/Glide   (22056): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
I/Glide   (22056): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/Glide   (22056): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/Glide   (22056): 	at java.lang.Thread.run(Thread.java:764)
I/Glide   (22056): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
I/Glide   (22056): Caused by: java.security.cert.CertificateException: Chain validation failed
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:719)
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:543)
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:564)
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:609)
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:609)
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:499)
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:422)
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:343)
I/Glide   (22056): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
I/Glide   (22056): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
I/Glide   (22056): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
I/Glide   (22056): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:426)
I/Glide   (22056): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
I/Glide   (22056): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
I/Glide   (22056): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
I/Glide   (22056): 	... 28 more
I/Glide   (22056): Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
I/Glide   (22056): 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
I/Glide   (22056): 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
I/Glide   (22056): 	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
I/Glide   (22056): 	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
I/Glide   (22056): 	at com.android.org.conscrypt.DelegatingCertPathValidator.engineValidate(DelegatingCertPathValidator.java:44)
I/Glide   (22056): 	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
I/Glide   (22056): 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:715)
I/Glide   (22056): 	... 42 more
I/Glide   (22056): Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
I/Glide   (22056): 	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
I/Glide   (22056): 	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
I/Glide   (22056): 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
I/Glide   (22056): 	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
I/Glide   (22056): 	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
I/Glide   (22056): 	... 48 more
I/Glide   (22056): 	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
I/Glide   (22056): 		at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
I/Glide   (22056): 		at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
I/Glide   (22056): 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
I/Glide   (22056): 		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
I/Glide   (22056): 		at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
I/Glide   (22056): 		... 50 more

**Comment by tudosxxx** [comment]
I use your demo
